# ----------------------------------------------------------------------------
# Customize Options:
title: Duo, A Jekyll Theme for Busy People
permalink: posts/:title/
baseurl: "/duo"
lang: "en"
date_format: "%b %-d, %Y"
url: "https://chibicode.github.io"
# Twitter IDs
twitter:
  username: "chibicode"
author:
  twitter: "chibicode"
# See: https://material.io/guidelines/style/color.html
# Use color-name-value, like pink-200 or deep-purple-400
brand_color: "yellow-500"
# "UA-NNNNNNNN-N"
google_analytics: ""
# Set default og:image
defaults:
  -
    scope:
      path: ""
    values:
      image: "/duo/images/og.png"
# ----------------------------------------------------------------------------

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - mix-manifest.json
  - webpack.mix.js
  - yarn.lock
  - package.json
  - hot

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji
  - jekyll-readme-index
