# ----------------------------------------------------------------------------
# Customize Options:
title: Duo, A Jekyll Theme for Busy People
permalink: :title
baseurl: "/duo"
lang: "en"
author: "Shu Uesugi"
date_format: "%b %-d, %Y"
twitter_account: "chibicode"
url: "https://chibicode.github.io"
# See: https://material.io/guidelines/style/color.html
# Use color-name-value, like pink-200 or deep-purple-400
brand_color: "yellow-500"
# "UA-NNNNNNNN-N"
google_analytics: ""
# ----------------------------------------------------------------------------

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - mix-manifest.json
  - webpack.mix.js
  - yarn.lock
  - package.json
  - hot

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "default"
